version: '3.8'

services:
  nginx:
    build: .
    container_name: nginx_waf
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/local/openresty/nginx/conf
      - ./influxdb/update_influxdb.sh:/usr/local/bin/update_influxdb.sh
    depends_on:
      - web_app
      - dashboard_app  # Ensure nginx waits for dashboard_app

  web_app:
    build: ./web_app  # This points to your Go web application directory
    container_name: go_web_app
    ports:
      - "8080:8080"  # Expose your Go app on port 8080
    networks:
      - default

  dashboard_app:
    build: ./dashboard_app  # Directory containing your dashboard service
    container_name: go_dashboard_app
    ports:
      - "8090:8090"  # Expose the dashboard API on port 8090
    depends_on:
      - influxdb  # Wait for InfluxDB to start before running dashboard app
    networks:
      - default
    environment:
      INFLUXDB_URL: "http://influxdb:8086"
      INFLUXDB_BUCKET: "api_metrics"
      INFLUXDB_ORG: "waf"
      MEASUREMENT: "api_requests"

  influxdb:
    image: influxdb:latest  # Or specify a version like influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086" # InfluxDB HTTP API
      - "8083:8083" # InfluxDB Admin UI (if applicable for the version)
    volumes:
      - influxdb_data:/var/lib/influxdb # Persist data across container restarts
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup # Initialize InfluxDB on first run
      - DOCKER_INFLUXDB_INIT_USERNAME=admin # Set initial username (optional, but good practice even without auth)
      - DOCKER_INFLUXDB_INIT_PASSWORD=password # Set initial password (optional, but good practice even without auth)
      - DOCKER_INFLUXDB_INIT_ORG=myorg # Set initial organization name
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket # Set initial bucket name
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken # Set initial admin token (optional, but good practice even without auth)
      - INFLUXDB_HTTP_AUTH_ENABLED=false # Disable authentication (THIS IS WHAT YOU ASKED FOR, BUT READ THE IMPORTANT NOTE BELOW)
    
volumes:
  influxdb_data: # Named volume for data persistence

networks:
  default:
    driver: bridge
